feat: csv handling param
gitcoinco/allo-indexer-client pull request #12
Opened 2023-04-27 03:32 UTC by hmrtn

2023-04-27 11:38 UTC, gravityblast requested changes

2023-04-27 11:38 UTC, gravityblast commented on src/client/baseClient.ts
> +        if (csv) {
@hmrtn instead of having a csv parameter we can parse the body based on the content type in the response header

2023-05-02 02:13 UTC, hmrtn commented
Reopened this in reference to: https://github.com/gitcoinco/allo-indexer/pull/56 in regards to the ticket: https://github.com/gitcoinco/grants-stack/issues/1475

2023-05-02 10:03 UTC, vacekj commented
https://github.com/gitcoinco/allo-indexer/pull/56#discussion_r1182348568

2023-05-02 16:26 UTC, hansmrtn commented
okie

2023-05-02 16:27 UTC, closed without merging